export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_POST = "GET_POST";
export const GET_ALL_POSTS_FAIL = "GET_ALL_POSTS_FAIL";
export const GET_ALL_POSTS_LOAD = "GET_ALL_POSTS_LOAD";
