export const GET_ALL_TOPICS_SUCCESS = "GET_ALL_TOPICS_SUCCESS";
export const GET_ALL_TOPICS_FAIL = "GET_ALL_TOPICS_FAIL";
export const GET_ALL_TOPICS_LOAD = "GET_ALL_TOPICS_LOAD";
export const GET_TOPIC = "GET_TOPIC";

